# Generated by Django 3.2.8 on 2021-11-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('location', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('R', 'Republic'), ('P', 'Pre hospital'), ('RF', 'RayFields'), ('BS', 'Bodyshop'), ('O', 'Other')], max_length=2)),
                ('status', models.CharField(choices=[('IS', 'In service'), ('B', 'Backup'), ('OC', 'On call'), ('ISO', 'In service -other'), ('OOS-M', 'Out of service -mechanical'), ('OOS-D', 'Out of service -dead'), ('OOS-O', 'Out of service -other')], max_length=5)),
                ('mileage', models.IntegerField()),
                ('insurance', models.BooleanField()),
                ('avl', models.IntegerField()),
                ('service_mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CADTablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EHRComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EightHundredMHZRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glucometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NarcoticBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sonim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonimCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VHFRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.ambulance')),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='auto_pulse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.autopulse'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='cad_tablet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.cadtablet'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='cot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.cot'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='ecg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.ecg'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='ehr_computer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.ehrcomputer'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='eighthundredmhz_radio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.eighthundredmhzradio'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='electronic_monitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.electronicmonitor'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='electronic_radio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.electronicradio'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='glucometer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.glucometer'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='narcotic_box',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.narcoticbox'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='sonim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.sonim'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='sonim_charger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.sonimcharger'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='suction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.suction'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='vhf_radio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to='tracker.vhfradio'),
        ),
    ]
